import Image from "next/image"
import { DoorClosed, DoorOpen } from "lucide-react"

import { Button } from "@/components/ui/button"
import { EXTERIOR_UPGRADES, TASKS } from "@/lib/game/constants"
import { SceneCharacter } from "./scene-character"

const names = { father: "Father", mother: "Mother", child: "Child" } as const

export function SceneVehicle({ exterior, fuel, carOpen, onToggle, characters, pairBonds, interaction }: { exterior: { level: number; id: keyof typeof EXTERIOR_UPGRADES }; fuel: number; carOpen: boolean; onToggle: () => void; characters: Record<keyof typeof names, { task: keyof typeof TASKS }>; pairBonds: { fatherMother: number; fatherChild: number; motherChild: number }; interaction: Record<keyof typeof names, { mode: "work" | "walk" | "meet"; bubble: string }> }) {
  const imageName = `car-${exterior.level === 1 ? "first" : exterior.level === 2 ? "second" : "third"}-${carOpen ? "open" : "close"}.webp`
  return <><div className={`truck truck-tier-${exterior.level} ${fuel <= 0 ? "truck-stopped" : ""}`}><Image src={`/image/cars/${imageName}`} alt={`${EXTERIOR_UPGRADES[exterior.id].label}, ${carOpen ? "open" : "closed"}`} fill priority className="truck-image" sizes="(max-width: 640px) 92vw, 480px" /><div className="truck-characters"><SceneCharacter name={names.mother} task={TASKS[characters.mother.task].label} position="mother" bond={pairBonds.motherChild} activity={interaction.mother} /><SceneCharacter name={names.child} task={TASKS[characters.child.task].label} position="child" bond={pairBonds.fatherChild} activity={interaction.child} /><SceneCharacter name={names.father} task={TASKS[characters.father.task].label} position="father" bond={pairBonds.fatherMother} activity={interaction.father} /></div></div><Button type="button" variant="outline" size="sm" className="absolute top-4 right-4 z-10 rounded-sm border-white/30 bg-[#202821]/80 text-[#ebe5d7] shadow-lg backdrop-blur-sm hover:bg-[#202821] lg:top-[16px] lg:right-[16px]" onClick={onToggle} aria-pressed={carOpen} title={carOpen ? "Close vehicle" : "Open vehicle"}>{carOpen ? <DoorClosed /> : <DoorOpen />}<span className="hidden sm:inline">{carOpen ? "Close" : "Open"}</span></Button><div className="vehicle-shell-meta absolute right-4 bottom-4 text-right text-[#eee7d8] drop-shadow-md lg:right-[16px] lg:bottom-[16px]"><p className="text-xs font-bold uppercase tracking-[0.16em] opacity-70 lg:text-[9px]">Vehicle shell</p><p className="text-sm font-semibold lg:text-[14px]">{EXTERIOR_UPGRADES[exterior.id].label}</p><p className="mt-1 text-xs uppercase tracking-[0.12em] opacity-60 lg:mt-[4px] lg:text-[10px]">{carOpen ? "Open for work." : "Closed for travel."}</p></div></>
}
